version: "3.8"
services:
  pharmacy-recommendation-database:
    container_name: multimodule-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: bumjin/multimodule-database
    environment:
      - MARIADB_DATABASE=multimodule
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"      # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)